"""Canonical thermal lane for source-backed He-4 support records."""

from .he4_normal_viscosity_kubo import physical_transport_record, source_hash
from .he4_o2_response_calibration import calibration_record
from .he4_o2_si_beta_mapping import si_beta_record
from .he4_svp_reference import (
    SOURCE_DOI,
    SOURCE_SNAPSHOT_BYTES,
    SOURCE_SNAPSHOT_SHA256,
    SOURCE_URL,
    T_LAMBDA_K,
    calibration_grid,
    reference_row,
    superfluid_density_kg_m3,
    total_density_kg_m3,
)

from .thermal_observable_bridge import (
    THERMAL_BRIDGE_STATUS,
    THERMAL_MAPPING_STATUS,
    ThermalObservableBridgeConfig,
    ThermalObservableBridgeResult,
    run_thermal_observable_bridge,
)
from .thermal_source_observable_map import (
    NORMALIZED_TTG_OBSERVABLE,
    THERMAL_CALIBRATION_SCHEMA_VERSION,
    THERMAL_CALIBRATION_STATUSES,
    THERMAL_SOURCE_MAP_SCHEMA_VERSION,
    ThermalPhiCalibration,
    normalized_ttg_signal,
    quasi_temperature_difference_from_calibration,
    quasi_temperature_difference_from_phi,
    ttg_propagation_length,
    ttg_wave_speed,
    ttg_wavevector,
)
from .thermal_dimensional_bridge import (
    ConditionalThermalInputs,
    alpha_phi_k_from_local_equilibrium,
    dimensional_bridge_unit_contract,
    effective_phi_curvature,
    entropy_density_J_per_m3_K,
    free_energy_density_J_per_m3,
    joint_delta_temperature_K,
)
from .thermal_energy_response_bridge import (
    EnergyResponseInputs,
    alpha_phi_e_k,
    alpha_phi_e_uncertainty_K,
    delta_tq_from_delta_u,
    named_energy_response_branch_contract,
    phi_e_from_delta_u,
    validate_energy_response_inputs,
)
from .thermal_phi_e_reference_normalization import (
    PhiEReferenceInputs,
    alpha_phi_e_K,
    phi_e_from_delta_u as phi_e_from_delta_u_reference,
    phi_e_reference_contract,
    reference_energy_density_J_per_m3,
)
from .thermal_response_beta_contract import (
    ThermalResponseBetaInputs,
    a_phi_of_temperature,
    beta_t13_from_stiffness_slope,
    da_phi_dT_per_K,
    entropy_density_J_per_m3_K as beta_entropy_density_J_per_m3_K,
    free_energy_density_J_per_m3 as beta_free_energy_density_J_per_m3,
    normalized_free_energy_density,
    thermal_response_beta_contract,
    validate_inputs as validate_thermal_response_beta_inputs,
)
__all__ = [
    "THERMAL_BRIDGE_STATUS",
    "THERMAL_MAPPING_STATUS",
    "ThermalObservableBridgeConfig",
    "ThermalObservableBridgeResult",
    "run_thermal_observable_bridge",
    "NORMALIZED_TTG_OBSERVABLE",
    "THERMAL_CALIBRATION_SCHEMA_VERSION",
    "THERMAL_CALIBRATION_STATUSES",
    "THERMAL_SOURCE_MAP_SCHEMA_VERSION",
    "ThermalPhiCalibration",
    "normalized_ttg_signal",
    "quasi_temperature_difference_from_calibration",
    "quasi_temperature_difference_from_phi",
    "ttg_propagation_length",
    "ttg_wave_speed",
    "ttg_wavevector",
    "ConditionalThermalInputs",
    "alpha_phi_k_from_local_equilibrium",
    "dimensional_bridge_unit_contract",
    "effective_phi_curvature",
    "entropy_density_J_per_m3_K",
    "free_energy_density_J_per_m3",
    "joint_delta_temperature_K",
    "EnergyResponseInputs",
    "alpha_phi_e_k",
    "alpha_phi_e_uncertainty_K",
    "delta_tq_from_delta_u",
    "named_energy_response_branch_contract",
    "phi_e_from_delta_u",
    "validate_energy_response_inputs",
    "PhiEReferenceInputs",
    "alpha_phi_e_K",
    "phi_e_from_delta_u_reference",
    "phi_e_reference_contract",
    "reference_energy_density_J_per_m3",
    "ThermalResponseBetaInputs",
    "a_phi_of_temperature",
    "beta_t13_from_stiffness_slope",
    "da_phi_dT_per_K",
    "beta_entropy_density_J_per_m3_K",
    "beta_free_energy_density_J_per_m3",
    "normalized_free_energy_density",
    "thermal_response_beta_contract",
    "validate_thermal_response_beta_inputs",
    "SOURCE_DOI",
    "SOURCE_SNAPSHOT_BYTES",
    "SOURCE_SNAPSHOT_SHA256",
    "SOURCE_URL",
    "T_LAMBDA_K",
    "calibration_grid",
    "calibration_record",
    "physical_transport_record",
    "reference_row",
    "si_beta_record",
    "source_hash",
    "superfluid_density_kg_m3",
    "total_density_kg_m3",
]
