"""Exact-kinematic action-derived two-to-two transition channels for Topic 13.

The lane samples elastic equal-mass two-to-two channels from the declared
constant-amplitude O(2) scattering kernel.  Each channel is generated by a
center-of-mass rotation and Lorentz boost, so charge, energy, and three-momentum
are conserved before the linearized channel vector is assembled.  The forward
and reverse Bose weights are checked separately for detailed balance.

This is a finite discrete transition-kernel interface.  It is not a connected
continuum collision operator, a microscopic Bethe-Salpeter vertex, a full SK
action match, a physical Kubo coefficient, or an SI observable.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import cos, cosh, exp, expm1, isfinite, pi, sin, sinh, sqrt

import numpy as np

from docs.core.uet_o2_finite_temperature_quasiparticle_eos import (
    FiniteTemperatureO2QuasiparticleConfig,
)
from docs.core.uet_o2_kinetic_collision_kubo import (
    _bose,
    _normal_state_inputs,
    _quadrature,
    _relative_velocity,
)


TRANSITION_KERNEL_STATUS = (
    "PASS_ACTION_DERIVED_EXACT_KINEMATIC_2TO2_TRANSITION_KERNEL_LANE"
)


@dataclass(frozen=True)
class TransitionKernelState:
    """Exact-kinematic transition-channel response quantities."""

    temperature: float
    chemical_potential: float
    space_response: float
    effective_mass: float
    momentum_cutoff: float
    quadrature_order: int
    channel_count: int
    state_count: int
    state_species_signs: tuple[float, ...]
    state_momenta: tuple[tuple[float, float, float], ...]
    state_energies: tuple[float, ...]
    state_charges: tuple[float, ...]
    state_weights: tuple[float, ...]
    channel_rates: tuple[float, ...]
    channel_reverse_rates: tuple[float, ...]
    channel_invariant_residuals: tuple[tuple[float, float, float, float, float], ...]
    channel_detailed_balance_residuals: tuple[float, ...]
    transition_vectors: tuple[tuple[float, ...], ...]
    collision_operator: tuple[tuple[float, ...], ...]
    collision_operator_eigenvalues: tuple[float, ...]
    invariant_matrix_rank: int
    null_mode_count: int
    collision_conservation_residual: float
    operator_symmetry_residual: float
    positive_semidefinite_min_eigenvalue: float
    source_vector: tuple[float, ...]
    active_source_vector: tuple[float, ...]
    source_active_projection_residual: float
    positive_mode_rate: float
    retarded_frequency_over_rate: tuple[float, ...]
    retarded_response_real: tuple[float, ...]
    retarded_response_imag: tuple[float, ...]
    dc_response: float
    kms_frequency_over_temperature: tuple[float, ...]
    kms_spectral_density: tuple[float, ...]
    kms_greater: tuple[float, ...]
    kms_lesser: tuple[float, ...]
    kms_noise: tuple[float, ...]
    kms_ratio: tuple[float, ...]
    kms_target_ratio: tuple[float, ...]
    kms_noise_target: tuple[float, ...]
    bs_frequency_over_rate: tuple[float, ...]
    bs_match_residuals: tuple[float, ...]
    entropy_production_witness: float
    exact_kinematics_declared: bool = True
    detailed_balance_checked: bool = True
    finite_channel_boundary_declared: bool = True
    microscopic_bethe_salpeter_match_completed: bool = False
    microscopic_sk_kms_match_completed: bool = False
    physical_kubo_coefficient_emitted: bool = False
    numeric_alpha_Phi_K_emitted: bool = False
    parameter_fitting_performed: bool = False
    target_data_used: bool = False
    xie_2026_accessed: bool = False
    data_role: str = (
        "ACTION_DERIVED_EXACT_KINEMATIC_2TO2_TRANSITION_KERNEL_NOT_MICROSCOPIC_VERTEX"
    )


def _finite(value: float, name: str) -> float:
    result = float(value)
    if not isfinite(result):
        raise ValueError(f"{name} must be finite")
    return result


def _positive(value: float, name: str) -> float:
    result = _finite(value, name)
    if result <= 0.0:
        raise ValueError(f"{name} must be positive")
    return result


def _bose_frequency(argument: float) -> float:
    x = _positive(argument, "beta frequency")
    return exp(-x) if x > 50.0 else 1.0 / expm1(x)


def _matrix_tuple(matrix: np.ndarray) -> tuple[tuple[float, ...], ...]:
    return tuple(tuple(float(value) for value in row) for row in matrix)


def _boost_from_center_of_mass(
    energy_star: float,
    momentum_star: np.ndarray,
    beta: np.ndarray,
) -> tuple[float, np.ndarray]:
    beta_sq = float(np.dot(beta, beta))
    if beta_sq <= 1.0e-15:
        return float(energy_star), np.asarray(momentum_star, dtype=float)
    gamma = 1.0 / sqrt(1.0 - beta_sq)
    parallel = float(np.dot(beta, momentum_star))
    energy = gamma * (energy_star + parallel)
    factor = (gamma - 1.0) * parallel / beta_sq + gamma * energy_star
    return float(energy), np.asarray(momentum_star, dtype=float) + factor * beta


def _retarded_response(
    source: np.ndarray,
    frequency: float,
    eigenvalues: np.ndarray,
    eigenvectors: np.ndarray,
) -> complex:
    projected = eigenvectors.T @ source
    response = 0.0j
    for coefficient, eigenvalue in zip(projected, eigenvalues):
        if eigenvalue <= 1.0e-14 and frequency == 0.0:
            continue
        response += float(coefficient * coefficient) / (eigenvalue - 1.0j * frequency)
    return complex(response)


def _bethe_salpeter_residual(
    operator: np.ndarray,
    frequency: float,
    reference_rate: float,
) -> float:
    identity = np.eye(operator.shape[0], dtype=float)
    bare = np.linalg.inv(reference_rate * identity - 1.0j * frequency * identity)
    kernel = reference_rate * identity - operator
    full = np.linalg.inv(operator - 1.0j * frequency * identity)
    ladder = bare + bare @ kernel @ full
    return float(np.linalg.norm(ladder - full) / max(np.linalg.norm(full), 1.0))


def _channel_directions(index: int) -> tuple[np.ndarray, np.ndarray]:
    directions = (
        np.array((1.0, 0.0, 0.0)),
        np.array((0.0, 1.0, 0.0)),
        np.array((0.0, 0.0, 1.0)),
        np.array((-1.0, 0.0, 0.0)),
        np.array((0.0, -1.0, 0.0)),
        np.array((0.0, 0.0, -1.0)),
    )
    return directions[index % len(directions)], directions[(index + 1) % len(directions)]


def action_derived_transition_kernel_state(
    temperature: float,
    chemical_potential: float,
    space_response: float,
    config: FiniteTemperatureO2QuasiparticleConfig | None = None,
    *,
    quadrature_order: int = 24,
    channel_count: int = 12,
    cutoff_factor: float = 36.0,
    retarded_frequency_over_rate: tuple[float, ...] = (0.0, 0.5, 1.0, 2.0),
    kms_frequency_over_temperature: tuple[float, ...] = (0.25, 0.5, 1.0),
    bs_frequency_over_rate: tuple[float, ...] = (0.5, 1.0, 2.0),
) -> TransitionKernelState:
    """Build exact-kinematic elastic channels and their formal response."""

    if isinstance(quadrature_order, bool) or int(quadrature_order) != quadrature_order:
        raise ValueError("quadrature_order must be an integer")
    if int(quadrature_order) < 24:
        raise ValueError("quadrature_order must be >= 24")
    if isinstance(channel_count, bool) or int(channel_count) != channel_count:
        raise ValueError("channel_count must be an integer")
    if int(channel_count) < 4:
        raise ValueError("channel_count must be >= 4")

    def _ordered_nonnegative(values: tuple[float, ...], name: str) -> tuple[float, ...]:
        if not values:
            raise ValueError(f"{name} must not be empty")
        result = tuple(_finite(value, name) for value in values)
        if tuple(sorted(result)) != result or any(value < 0.0 for value in result):
            raise ValueError(f"{name} must be sorted and non-negative")
        return result

    response_ratios = _ordered_nonnegative(
        retarded_frequency_over_rate, "retarded_frequency_over_rate"
    )
    if response_ratios[0] != 0.0:
        raise ValueError("retarded_frequency_over_rate must start at zero")
    kms_ratios = tuple(
        _positive(value, "kms_frequency_over_temperature")
        for value in kms_frequency_over_temperature
    )
    if tuple(sorted(kms_ratios)) != kms_ratios:
        raise ValueError("kms_frequency_over_temperature must be sorted")
    bs_ratios = tuple(
        _positive(value, "bs_frequency_over_rate") for value in bs_frequency_over_rate
    )
    if tuple(sorted(bs_ratios)) != bs_ratios:
        raise ValueError("bs_frequency_over_rate must be sorted")

    config = config or FiniteTemperatureO2QuasiparticleConfig()
    t, mu, mass, mu_eff, quartic = _normal_state_inputs(
        temperature, chemical_potential, space_response, config
    )
    cutoff_factor = _positive(cutoff_factor, "cutoff_factor")
    cutoff = max(cutoff_factor * t, cutoff_factor * mass, cutoff_factor * mu_eff, 1.0)
    nodes, weights = _quadrature(int(quadrature_order), cutoff)
    directions = [_channel_directions(index) for index in range(channel_count)]
    signs = ((-1.0, 1.0), (1.0, 1.0), (-1.0, -1.0))

    state_signs: list[float] = []
    state_momenta: list[tuple[float, float, float]] = []
    state_energies: list[float] = []
    state_charges: list[float] = []
    state_weights: list[float] = []
    channel_rates: list[float] = []
    channel_reverse_rates: list[float] = []
    channel_invariant_residuals: list[tuple[float, float, float, float, float]] = []
    channel_balance_residuals: list[float] = []
    transition_vectors: list[np.ndarray] = []
    radial_measure = 1.0 / (2.0 * np.pi * np.pi)

    def add_state(sign: float, momentum: np.ndarray, energy: float, weight: float) -> int:
        index = len(state_signs)
        state_signs.append(float(sign))
        state_momenta.append(tuple(float(value) for value in momentum))
        state_energies.append(float(energy))
        state_charges.append(float(sign))
        state_weights.append(_positive(weight, "channel state weight"))
        return index

    for index in range(int(channel_count)):
        node_one = int((2 * index + 3) % (int(quadrature_order) - 3))
        node_two = int((3 * index + 7) % (int(quadrature_order) - 3))
        p_one = float(nodes[node_one + 2])
        p_two = float(nodes[node_two + 2])
        direction_one, direction_two = directions[index]
        momentum_one = p_one * direction_one
        momentum_two = p_two * direction_two
        energy_one = sqrt(p_one * p_one + mass * mass)
        energy_two = sqrt(p_two * p_two + mass * mass)
        sign_one, sign_two = signs[index % len(signs)]
        total_energy = energy_one + energy_two
        total_momentum = momentum_one + momentum_two
        invariant_s = total_energy * total_energy - float(np.dot(total_momentum, total_momentum))
        root_s = sqrt(_positive(invariant_s, "two-body invariant mass squared"))
        p_star = sqrt(max(invariant_s / 4.0 - mass * mass, 0.0))
        energy_star = root_s / 2.0
        beta = total_momentum / total_energy
        polar = 0.32 + 0.11 * float((index % 7) + 1)
        azimuth = 0.41 * float(index + 1)
        outgoing_direction = np.array(
            (
                sin(polar) * cos(azimuth),
                sin(polar) * sin(azimuth),
                cos(polar),
            )
        )
        energy_three, momentum_three = _boost_from_center_of_mass(
            energy_star, p_star * outgoing_direction, beta
        )
        energy_four = total_energy - energy_three
        momentum_four = total_momentum - momentum_three
        p_three = float(np.linalg.norm(momentum_three))
        p_four = float(np.linalg.norm(momentum_four))
        energy_three = sqrt(_positive(mass * mass + p_three * p_three, "outgoing energy three"))
        energy_four = sqrt(_positive(mass * mass + p_four * p_four, "outgoing energy four"))

        relative, two_body_s = _relative_velocity(
            energy_one,
            energy_two,
            p_one,
            p_two,
            float(np.dot(direction_one, direction_two)),
            mass * mass,
        )
        cross_section = quartic * quartic / (16.0 * pi * two_body_s)
        f_one = _bose(energy_one - sign_one * mu_eff, t)
        f_two = _bose(energy_two - sign_two * mu_eff, t)
        f_three = _bose(energy_three - sign_one * mu_eff, t)
        f_four = _bose(energy_four - sign_two * mu_eff, t)
        forward_weight = f_one * f_two * (1.0 + f_three) * (1.0 + f_four)
        reverse_weight = f_three * f_four * (1.0 + f_one) * (1.0 + f_two)
        balance_residual = abs(forward_weight - reverse_weight) / max(forward_weight, reverse_weight, 1.0e-300)
        channel_balance_residuals.append(float(balance_residual))
        phase_measure = (
            float(weights[node_one + 2])
            * float(weights[node_two + 2])
            * p_one
            * p_one
            * p_two
            * p_two
            * radial_measure
            * radial_measure
        )
        rate = _positive(phase_measure * relative * cross_section * forward_weight, "channel rate")
        channel_rates.append(rate)
        reverse_rate = _positive(
            phase_measure * relative * cross_section * reverse_weight,
            "reverse channel rate",
        )
        channel_reverse_rates.append(reverse_rate)
        leg_weight_one = _positive(float(weights[node_one + 2]) * p_one * p_one * radial_measure * f_one * (1.0 + f_one) / t, "incoming state weight one")
        leg_weight_two = _positive(float(weights[node_two + 2]) * p_two * p_two * radial_measure * f_two * (1.0 + f_two) / t, "incoming state weight two")
        leg_weight_three = _positive(cutoff / float(channel_count) * p_three * p_three * radial_measure * f_three * (1.0 + f_three) / t, "outgoing state weight three")
        leg_weight_four = _positive(cutoff / float(channel_count) * p_four * p_four * radial_measure * f_four * (1.0 + f_four) / t, "outgoing state weight four")
        leg_indices = (
            add_state(sign_one, momentum_one, energy_one, leg_weight_one),
            add_state(sign_two, momentum_two, energy_two, leg_weight_two),
            add_state(sign_one, momentum_three, energy_three, leg_weight_three),
            add_state(sign_two, momentum_four, energy_four, leg_weight_four),
        )
        vector = np.zeros(4 * int(channel_count), dtype=float)
        vector[leg_indices[0]] += 1.0 / sqrt(leg_weight_one)
        vector[leg_indices[1]] += 1.0 / sqrt(leg_weight_two)
        vector[leg_indices[2]] -= 1.0 / sqrt(leg_weight_three)
        vector[leg_indices[3]] -= 1.0 / sqrt(leg_weight_four)
        transition_vectors.append(vector)
        channel_invariant_residuals.append(
            (
                sign_one + sign_two - sign_one - sign_two,
                energy_one + energy_two - energy_three - energy_four,
                float(momentum_one[0] + momentum_two[0] - momentum_three[0] - momentum_four[0]),
                float(momentum_one[1] + momentum_two[1] - momentum_three[1] - momentum_four[1]),
                float(momentum_one[2] + momentum_two[2] - momentum_three[2] - momentum_four[2]),
            )
        )

    state_count = len(state_signs)
    weight_array = np.asarray(state_weights, dtype=float)
    energy_array = np.asarray(state_energies, dtype=float)
    charge_array = np.asarray(state_charges, dtype=float)
    momentum_array = np.asarray(state_momenta, dtype=float)
    invariant_matrix = np.column_stack(
        (
            charge_array * np.sqrt(weight_array),
            energy_array * np.sqrt(weight_array),
            momentum_array[:, 0] * np.sqrt(weight_array),
            momentum_array[:, 1] * np.sqrt(weight_array),
            momentum_array[:, 2] * np.sqrt(weight_array),
        )
    )
    invariant_rank = int(np.linalg.matrix_rank(invariant_matrix, tol=1.0e-12))
    transition_matrix = np.asarray(transition_vectors, dtype=float).T
    rates_array = np.asarray(channel_rates, dtype=float)
    operator = transition_matrix @ np.diag(rates_array) @ transition_matrix.T
    eigenvalues, eigenvectors = np.linalg.eigh(operator)
    positive_eigenvalues = eigenvalues[eigenvalues > 1.0e-14]
    positive_rate = _positive(float(np.mean(positive_eigenvalues)), "positive mode rate")
    source_array = charge_array * momentum_array[:, 0] / energy_array * np.sqrt(weight_array)
    active_vectors = eigenvectors[:, eigenvalues > 1.0e-14]
    active_source = active_vectors @ (active_vectors.T @ source_array)
    frequencies = tuple(positive_rate * ratio for ratio in response_ratios)
    responses = tuple(
        _retarded_response(active_source, frequency, eigenvalues, eigenvectors)
        for frequency in frequencies
    )
    kms_frequencies = tuple(t * ratio for ratio in kms_ratios)
    kms_responses = tuple(
        _retarded_response(active_source, frequency, eigenvalues, eigenvectors)
        for frequency in kms_frequencies
    )
    spectral = tuple(2.0 * response.imag for response in kms_responses)
    occupations = tuple(_bose_frequency(ratio) for ratio in kms_ratios)
    greater = tuple(rho * (1.0 + occupation) for rho, occupation in zip(spectral, occupations))
    lesser = tuple(rho * occupation for rho, occupation in zip(spectral, occupations))
    noise = tuple(g + l for g, l in zip(greater, lesser))
    target_ratio = tuple(exp(ratio) for ratio in kms_ratios)
    kms_ratio = tuple(g / l for g, l in zip(greater, lesser))
    noise_target = tuple(
        rho * cosh(0.5 * ratio) / sinh(0.5 * ratio)
        for rho, ratio in zip(spectral, kms_ratios)
    )
    bs_frequencies = tuple(positive_rate * ratio for ratio in bs_ratios)
    bs_residuals = tuple(
        _bethe_salpeter_residual(operator, frequency, positive_rate)
        for frequency in bs_frequencies
    )
    entropy_witness = _positive(
        float(np.dot(active_source, operator @ active_source) / t),
        "entropy production witness",
    )
    conservation_residual = float(np.linalg.norm(operator @ invariant_matrix))
    source_active_residual = float(np.linalg.norm(source_array - active_source))
    symmetry_residual = float(np.linalg.norm(operator - operator.T))
    values = (
        *eigenvalues,
        *[response.real for response in responses],
        *[response.imag for response in responses],
        *spectral,
        *greater,
        *lesser,
        *noise,
        *kms_ratio,
        *noise_target,
        *bs_residuals,
        entropy_witness,
    )
    if not all(isfinite(float(value)) for value in values):
        raise FloatingPointError("transition-kernel response is not finite")

    return TransitionKernelState(
        temperature=t,
        chemical_potential=mu,
        space_response=float(space_response),
        effective_mass=mass,
        momentum_cutoff=float(cutoff),
        quadrature_order=int(quadrature_order),
        channel_count=int(channel_count),
        state_count=state_count,
        state_species_signs=tuple(state_signs),
        state_momenta=tuple(state_momenta),
        state_energies=tuple(state_energies),
        state_charges=tuple(state_charges),
        state_weights=tuple(state_weights),
        channel_rates=tuple(channel_rates),
        channel_reverse_rates=tuple(channel_reverse_rates),
        channel_invariant_residuals=tuple(channel_invariant_residuals),
        channel_detailed_balance_residuals=tuple(channel_balance_residuals),
        transition_vectors=_matrix_tuple(transition_matrix.T),
        collision_operator=_matrix_tuple(operator),
        collision_operator_eigenvalues=tuple(float(value) for value in eigenvalues),
        invariant_matrix_rank=invariant_rank,
        null_mode_count=int(np.sum(eigenvalues <= 1.0e-14)),
        collision_conservation_residual=conservation_residual,
        operator_symmetry_residual=symmetry_residual,
        positive_semidefinite_min_eigenvalue=float(np.min(eigenvalues)),
        source_vector=tuple(float(value) for value in source_array),
        active_source_vector=tuple(float(value) for value in active_source),
        source_active_projection_residual=source_active_residual,
        positive_mode_rate=positive_rate,
        retarded_frequency_over_rate=response_ratios,
        retarded_response_real=tuple(float(response.real) for response in responses),
        retarded_response_imag=tuple(float(response.imag) for response in responses),
        dc_response=float(responses[0].real),
        kms_frequency_over_temperature=kms_ratios,
        kms_spectral_density=spectral,
        kms_greater=greater,
        kms_lesser=lesser,
        kms_noise=noise,
        kms_ratio=kms_ratio,
        kms_target_ratio=target_ratio,
        kms_noise_target=noise_target,
        bs_frequency_over_rate=bs_ratios,
        bs_match_residuals=bs_residuals,
        entropy_production_witness=entropy_witness,
    )


def action_derived_transition_kernel_contract() -> dict[str, object]:
    """Return equations, units, and the finite-kernel boundary."""

    return {
        "status": TRANSITION_KERNEL_STATUS,
        "equations": {
            "elastic_kinematics": "p1+p2=p3+p4; E1+E2=E3+E4; E_i=sqrt(p_i^2+m_eff^2)",
            "action_cross_section": "sigma_22=lambda^2/(16*pi*s)",
            "forward_weight": "W_f=f1*f2*(1+f3)*(1+f4)*v_rel*sigma_22*dmu",
            "reverse_weight": "W_r=f3*f4*(1+f1)*(1+f2)*v_rel*sigma_22*dmu",
            "detailed_balance": "W_f=W_r at declared equilibrium because energy and charge are conserved",
            "channel_vector": "v_c=(+1/sqrt(w1),+1/sqrt(w2),-1/sqrt(w3),-1/sqrt(w4))",
            "collision_operator": "L=sum_c W_c*v_c*v_c^T; L>=0; L*I_A=0",
            "retarded_response": "G_R=(L-i*omega*I)^(-1); K_R=b_active^T*G_R*b_active",
            "bethe_salpeter_identity": "G_0=(gamma_ref*I-i*omega*I)^(-1); K_BS=gamma_ref*I-L; G_R=G_0+G_0*K_BS*G_R",
            "kms_ratio": "G^>/G^<=exp(beta_th*omega)",
            "fdt_noise": "N=G^>+G^<=rho*coth(beta_th*omega/2)",
            "entropy_witness": "sigma_formal=b_active^T*L*b_active/T>=0",
        },
        "unit_contract": {
            "unit_lane": "natural",
            "temperature_chemical_potential_mass_momentum_energy": "energy",
            "cross_section": "inverse energy squared",
            "transition_rate": "formal natural-unit channel rate",
            "response_spectral_density_entropy_production": "formal natural-unit lane quantities",
            "Phi": "effective response variable; not temperature",
            "C": "collective system-behaviour coordinate; not mass or charge",
            "R_gen": "derived history trace; no backreaction",
            "R_obs": "separate observer record",
        },
        "derivation_class": (
            "action-derived constant-amplitude elastic two-to-two cross section, exact "
            "center-of-mass kinematics, Bose detailed balance, and finite channel outer products"
        ),
        "observable": "finite exact-kinematic channel response and formal transition-kernel/KMS interface",
        "data_role": "ACTION_DERIVED_EXACT_KINEMATIC_2TO2_TRANSITION_KERNEL_NOT_MICROSCOPIC_VERTEX",
        "included": {
            "exact_elastic_energy_momentum_conservation": True,
            "charge_conservation": True,
            "action_derived_cross_section": True,
            "forward_reverse_detailed_balance": True,
            "positive_semidefinite_channel_operator": True,
            "algebraic_bethe_salpeter_identity": True,
            "algebraic_sk_kms_fdt_interface": True,
        },
        "excluded": {
            "connected_continuum_collision_operator": True,
            "microscopic_bethe_salpeter_vertex": True,
            "microscopic_sk_action_match": True,
            "finite_channel_limit": True,
            "physical_kubo_coefficient": True,
            "entropy_current_in_curved_3_plus_1": True,
            "SI_map": True,
            "alpha_Phi_K": True,
            "TTG_validation": True,
        },
        "claim_boundary": (
            "This closes only a finite exact-kinematic action-derived two-to-two transition "
            "kernel and detailed-balance response interface. It is not a connected continuum "
            "collision operator, microscopic Bethe-Salpeter vertex, SK action match, physical "
            "Kubo coefficient, SI map, alpha_Phi_K calibration, TTG validation, or Full Topic 13 closure."
        ),
    }


__all__ = [
    "TRANSITION_KERNEL_STATUS",
    "TransitionKernelState",
    "action_derived_transition_kernel_state",
    "action_derived_transition_kernel_contract",
]
