import pandas as pd
import numpy as np
import os

# --- AUDIT CONFIG ---
REAL_DATA_DIR = r"c:\Users\santa\Desktop\lad\Lab_uet_harness_v0.8.7\research_v3\01_data"
V3_DATA_DIR = (
    r"c:\Users\santa\Desktop\lad\Lab_uet_harness_v0.8.7\research_v3\03_universal_physics\data"
)


def check_real_file(name, path):
    print(f"\n🔎 AUDIT: Checking Real Data '{name}'...")
    if os.path.exists(path):
        print(f"   ✅ FOUND: {path}")
        try:
            df = pd.read_csv(path, comment="#")
            print(f"   📊 ROWS: {len(df)}")
            print(f"   👀 SAMPLE:\n{df.head(3).to_string()}")
            return True
        except Exception as e:
            print(f"   ❌ READ ERROR: {e}")
            return False
    else:
        print(f"   ❌ MISSING: {path}")
        return False


def check_simulation_code(name, script_path, keyword):
    print(f"\n🔎 AUDIT: Checking Simulation Logic '{name}'...")
    if os.path.exists(script_path):
        print(f"   ✅ FOUND SCRIPT: {script_path}")
        with open(script_path, "r") as f:
            lines = f.readlines()

        found = False
        for i, line in enumerate(lines):
            if keyword in line:
                print(f"   📝 LOGIC FOUND (Line {i+1}): {line.strip()}")
                found = True
                break

        if not found:
            print(f"   ⚠️ WARNING: Keyword '{keyword}' not found in script.")
        return found
    else:
        print(f"   ❌ SCRIPT MISSING: {script_path}")
        return False


def run_integrity_check():
    print("╔════════════════════════════════════════════════════════╗")
    print("║             UET INTEGRITY AUDIT PROTOCOL               ║")
    print("╚════════════════════════════════════════════════════════╝")
    print("Goal: Prove which data is REAL and which is SIMULATED.")

    # 1. REAL LEGACY DATA (The "Hard Proof")
    print("\n--- [CATEGORY 1: REAL LEGACY DATA] (Found in your machine) ---")
    check_real_file("S&P 500", os.path.join(REAL_DATA_DIR, "sp500_bubble.csv"))
    check_real_file("HRV (Biology)", os.path.join(V3_DATA_DIR, "Biology_HRV.csv"))
    check_real_file("Social Networks", os.path.join(V3_DATA_DIR, "Sociology_Polarization.csv"))
    check_real_file("Enron Emails", os.path.join(V3_DATA_DIR, "Network_Enron.txt"))

    # 2. SIMULATED DATA (The "Physics Models")
    print("\n--- [CATEGORY 2: SIMULATED PHYSICS] (Generated by Code) ---")
    sim_script = r"c:\Users\santa\Desktop\lad\Lab_uet_harness_v0.8.7\research_v3\03_universal_physics\advanced_stress_test.py"

    check_simulation_code("Quantum (Schrodinger)", sim_script, "E_vals = (n_vals**2) * prefactor")
    check_simulation_code("Neural (Weber Law)", sim_script, "rate = np.log10(I) * 10")
    check_simulation_code("Gradient (Convergence)", sim_script, "loss = 1.0 / t_steps")

    print("\n" + "=" * 60)
    print("VERDICT:")
    print("1. Economics, Biology, Networks = REAL FILES (You can open them).")
    print("2. Quantum, Neurons, Gradient = CODE LOGIC (Based on Equations).")
    print("   (User did not provide raw Quantum/Neural files, so we simulated standard laws).")
    print("=" * 60)


if __name__ == "__main__":
    run_integrity_check()
