"""Finish the two remaining legacy README boundaries in the core migration.

The canonical area READMEs already exist under ``06_data`` and ``04_proofs``.
This runner therefore preserves those canonical documents and converts the old
boundary READMEs into explicit compatibility redirects.  If a future checkout
does not contain a canonical target, the source README is moved first and then
the legacy path is replaced by the same redirect.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
GOVERNANCE = ROOT / "docs" / "core" / "00_governance"
OUTPUT = GOVERNANCE / "uet_core_boundary_readmes_migration_v3.json"
PLANNER = ROOT / "docs/scripts/audit/plan_uet_core_physical_migration.py"
GENERATOR = "docs/scripts/audit/migrate_uet_core_boundary_readmes_v3.py"

MAPPINGS = (
    ("docs/core/data/README.md", "docs/core/06_data/README.md"),
    ("docs/core/02_Proof/README.md", "docs/core/04_proofs/README.md"),
)
TEXT_SUFFIXES = {".md", ".py", ".ps1", ".sh", ".yml", ".yaml", ".toml"}
REDIRECT_MARKER = "# Compatibility redirect"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def repo_path(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def relative_link(source: Path, target: Path) -> str:
    return Path(os.path.relpath(target, start=source.parent)).as_posix()


def redirect_text(old: Path, new: Path) -> str:
    canonical = repo_path(new)
    return (
        f"{REDIRECT_MARKER}\n\n"
        "> This legacy boundary is retained temporarily for compatibility.\n\n"
        f"Canonical source: [{canonical}]({relative_link(old, new)})\n\n"
        "Do not edit this file; update the canonical source instead.\n"
    )


def redirect_target(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    match = re.search(r"Canonical source: \[[^\]]+\]\(([^)]+)\)", text)
    if match is None:
        return None
    return repo_path((path.parent / match.group(1)).resolve())


def reference_files() -> list[Path]:
    roots = [ROOT / "docs", ROOT / "WORK_LEDGER", ROOT / "uet_history"]
    roots.extend((ROOT / name for name in ("README.md", "AGENTS.md")))
    paths: list[Path] = []
    for base in roots:
        if base.is_file():
            candidates = [base]
        elif base.exists():
            candidates = list(base.rglob("*"))
        else:
            candidates = []
        for path in candidates:
            if not path.is_file() or path == Path(__file__):
                continue
            if any(part in {".git", "__pycache__"} for part in path.parts):
                continue
            if path.suffix.lower() in TEXT_SUFFIXES:
                paths.append(path)
    return sorted(set(paths))


def build_preflight() -> dict[str, Any]:
    moves: list[dict[str, Any]] = []
    missing: list[str] = []
    conflicts: list[str] = []
    for legacy, canonical in MAPPINGS:
        old = ROOT / legacy
        new = ROOT / canonical
        if not old.exists():
            missing.append(legacy)
            continue
        target_exists = new.exists()
        if target_exists and new.suffix.lower() != ".md":
            conflicts.append(canonical)
        moves.append(
            {
                "legacy_path": legacy,
                "canonical_path": canonical,
                "source_sha256_before": sha256(old),
                "canonical_target_exists_before": target_exists,
                "canonical_sha256_before": sha256(new) if target_exists else None,
                "already_redirect": redirect_target(old) == canonical,
            }
        )

    references: list[dict[str, Any]] = []
    for path in reference_files():
        before = path.read_text(encoding="utf-8")
        after = before
        replacement_count = 0
        for legacy, canonical in MAPPINGS:
            for token in (legacy, legacy.replace("/", "\\")):
                replacement_count += after.count(token)
                after = after.replace(token, canonical)
        if after != before:
            references.append(
                {
                    "path": repo_path(path),
                    "sha256_before": hashlib.sha256(before.encode("utf-8")).hexdigest(),
                    "sha256_after": hashlib.sha256(after.encode("utf-8")).hexdigest(),
                    "replacement_count": replacement_count,
                    "text": after,
                }
            )
    return {"moves": moves, "references": references, "missing": missing, "conflicts": conflicts}


def apply(preflight: dict[str, Any]) -> dict[str, Any]:
    if preflight["missing"] or preflight["conflicts"]:
        raise RuntimeError(
            json.dumps(
                {"missing": preflight["missing"], "conflicts": preflight["conflicts"]},
                ensure_ascii=False,
            )
        )

    for item in preflight["references"]:
        (ROOT / item["path"]).write_text(item["text"], encoding="utf-8")

    applied: list[dict[str, Any]] = []
    for item in preflight["moves"]:
        old = ROOT / item["legacy_path"]
        new = ROOT / item["canonical_path"]
        source_hash = sha256(old)
        physical_move = False
        if not item["already_redirect"]:
            if not new.exists():
                new.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(old), str(new))
                physical_move = True
            elif new.resolve() == old.resolve():
                raise RuntimeError(f"canonical target aliases legacy source: {item['legacy_path']}")
            old.parent.mkdir(parents=True, exist_ok=True)
            old.write_text(redirect_text(old, new), encoding="utf-8")
        if not new.exists():
            raise RuntimeError(f"canonical target missing after migration: {item['canonical_path']}")
        applied.append(
            {
                **item,
                "source_sha256_before": source_hash,
                "canonical_sha256_after": sha256(new),
                "redirect_sha256_after": sha256(old),
                "physical_move_performed": physical_move,
                "migration_state": "MIGRATED_WITH_SHIM",
                "compatibility_mode": "markdown_redirect",
            }
        )

    subprocess.run([sys.executable, str(PLANNER), "--plan"], cwd=ROOT, check=True)
    payload = {
        "schema_version": "1.0",
        "artifact": "uet_core_boundary_readmes_migration_v3",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "generator": GENERATOR,
        "status": "PASS",
        "physical_move_performed": any(item["physical_move_performed"] for item in applied),
        "physics_status_changes": 0,
        "summary": {
            "files_selected": len(MAPPINGS),
            "files_reconciled": len(applied),
            "redirects_created_or_confirmed": len(applied),
            "canonical_targets_preserved": sum(item["canonical_target_exists_before"] for item in applied),
            "physical_moves_performed": sum(item["physical_move_performed"] for item in applied),
            "reference_files_changed": len(preflight["references"]),
            "reference_replacements": sum(item["replacement_count"] for item in preflight["references"]),
            "physics_status_changes": 0,
        },
        "moves": applied,
        "reference_changes": [{key: value for key, value in item.items() if key != "text"} for item in preflight["references"]],
        "claim_boundary": "physical organization and compatibility only; no physics/evidence promotion",
    }
    OUTPUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    if args.check and args.apply:
        parser.error("--check and --apply are mutually exclusive")
    preflight = build_preflight()
    ready = not preflight["missing"] and not preflight["conflicts"]
    if args.apply:
        payload = apply(preflight)
        print(json.dumps({"status": payload["status"], **payload["summary"]}, ensure_ascii=False, indent=2))
        return 0
    print(
        json.dumps(
            {
                "status": "PASS" if ready else "BLOCKED",
                "files_selected": len(preflight["moves"]),
                "reference_files_to_rewrite": len(preflight["references"]),
                "reference_replacements": sum(item["replacement_count"] for item in preflight["references"]),
                "missing": preflight["missing"],
                "conflicts": preflight["conflicts"],
                "targets_already_present": sum(item["canonical_target_exists_before"] for item in preflight["moves"]),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0 if ready else 1


if __name__ == "__main__":
    raise SystemExit(main())
