# Full UET Research Inventory (Topics 0-26)
# Provided by User Execution Mandate

UET_INVENTORY = {
    "Topic 0: Grand Unification": [
        "docs/topics/0.0_Grand_Unification/Code/01_Engine/Engine_Omni.py",
        "docs/topics/0.0_Grand_Unification/Code/02_Proof/Proof_Grand_Unification.py",
        "docs/topics/0.0_Grand_Unification/Code/03_Research/Verify_Omni.py",
    ],
    "Topic 1: Galaxy Rotation": [
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/01_Engine/Engine_Galaxy_V3.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/01_Engine/Data_Loader_SPARC.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/02_Proof/Proof_Unity_Density_Law.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/03_Research/Research_Alpha_Learning.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/03_Research/Research_Galaxy_Rotation.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/03_Research/Research_Dwarf_Galaxies.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/03_Research/Research_Residual_Analysis.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/03_Research/Verify_Galaxy_Rotation.py",
        "docs/topics/0.1_Galaxy_Rotation_Problem/Code/04_Competitor/Competitor_NFW.py",
    ],
    "Topic 2: Black Hole Physics": [
        "docs/topics/0.2_Black_Hole_Physics/Code/01_Engine/Engine_BlackHole.py",
        "docs/topics/0.2_Black_Hole_Physics/Code/01_Engine/Engine_Supersonic_Sink.py",
        "docs/topics/0.2_Black_Hole_Physics/Code/02_Proof/Proof_Singularity_Resolution.py",
        "docs/topics/0.2_Black_Hole_Physics/Code/03_Research/Research_CCBH_Analysis.py",
        "docs/topics/0.2_Black_Hole_Physics/Code/03_Research/Research_EHT_Validation.py",
        "docs/topics/0.2_Black_Hole_Physics/Code/03_Research/Research_GW_Validation.py",
        "docs/topics/0.2_Black_Hole_Physics/Code/03_Research/Research_Singularity_Sweep.py",
        "docs/topics/0.2_Black_Hole_Physics/Code/04_Competitor/Competitor_GR_Benchmark.py",
    ],
    "Topic 3: Cosmology & Hubble Tension": [
        "docs/topics/0.3_Cosmology_Hubble_Tension/Code/01_Engine/Engine_Cosmology.py",
        "docs/topics/0.3_Cosmology_Hubble_Tension/Code/02_Proof/Proof_Hubble_Resolution.py",
        "docs/topics/0.3_Cosmology_Hubble_Tension/Code/03_Research/Research_Hubble_Comparison.py",
        "docs/topics/0.3_Cosmology_Hubble_Tension/Code/03_Research/Research_Dark_Energy.py",
        "docs/topics/0.3_Cosmology_Hubble_Tension/Code/03_Research/Research_CMB_Analysis.py",
        "docs/topics/0.3_Cosmology_Hubble_Tension/Code/03_Research/Research_highz_galaxies.py",
        "docs/topics/0.3_Cosmology_Hubble_Tension/Code/04_Competitor/Competitor_Comparison_BAO.py",
    ],
    "Topic 4: Superconductivity": [
        "docs/topics/0.4_Superconductivity_Superfluids/Code/01_Engine/Engine_Superconductivity.py",
        "docs/topics/0.4_Superconductivity_Superfluids/Code/02_Proof/Proof_Cooper_Pairing.py",
        "docs/topics/0.4_Superconductivity_Superfluids/Code/03_Research/Experiment_Superconductor_Data.py",
        "docs/topics/0.4_Superconductivity_Superfluids/Code/03_Research/Research_Superconductivity.py",
        "docs/topics/0.4_Superconductivity_Superfluids/Code/03_Research/Research_Quantum_Phenomena.py",
        "docs/topics/0.4_Superconductivity_Superfluids/Code/03_Research/Research_Superfluids.py",
        "docs/topics/0.4_Superconductivity_Superfluids/Code/04_Competitor/Competitor_Standard_Model_Super.py",
        "docs/topics/0.4_Superconductivity_Superfluids/Code/04_Competitor/super_solver.py",
    ],
    "Topic 5: Nuclear Binding & Hadrons": [
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/01_Engine/Engine_Nuclear_Binding.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/01_Engine/Engine_Hadron_Model.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/01_Engine/Engine_Light_Nuclei.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/01_Engine/Engine_QCD_Bridge.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/02_Proof/Proof_Color_Confinement.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/03_Research/Research_Nuclear_Binding.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/03_Research/Research_Proton_Radius.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/03_Research/Research_QCD_Running.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/03_Research/Research_Quark_Masses.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/03_Research/Research_Strong_Force.py",
        "docs/topics/0.5_Nuclear_Binding_Hadrons/Code/04_Competitor/Competitor_Nuclear_Baseline.py",
    ],
    "Topic 6: Electroweak Physics": [
        "docs/topics/0.6_Electroweak_Physics/Code/01_Engine/Engine_Electroweak.py",
        "docs/topics/0.6_Electroweak_Physics/Code/02_Proof/Proof_WZ_Ratio.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_Alpha_Decay.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_Beta_Minus.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_Beta_Plus.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_Electroweak.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_Higgs_Mechanism.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_Neutron_Decay.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_Sin2_Theta_W_Running.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Research_W_Mass_Anomaly_Exp.py",
        "docs/topics/0.6_Electroweak_Physics/Code/03_Research/Verify_Electroweak.py",
        "docs/topics/0.6_Electroweak_Physics/Code/04_Competitor/Competitor_Electroweak_Baseline.py",
        "docs/topics/0.6_Electroweak_Physics/Code/04_Competitor/electroweak_solver.py",
    ],
    "Topic 7: Neutrino Physics": [
        "docs/topics/0.7_Neutrino_Physics/Code/01_Engine/Engine_Mixing_Neutrino.py",
        "docs/topics/0.7_Neutrino_Physics/Code/01_Engine/Engine_Neutrino.py",
        "docs/topics/0.7_Neutrino_Physics/Code/02_Proof/Proof_PMNS_Angles.py",
        "docs/topics/0.7_Neutrino_Physics/Code/03_Research/Research_Ft_Values.py",
        "docs/topics/0.7_Neutrino_Physics/Code/03_Research/Research_Neutrino.py",
        "docs/topics/0.7_Neutrino_Physics/Code/03_Research/Research_Neutrino_Extended.py",
        "docs/topics/0.7_Neutrino_Physics/Code/03_Research/Research_Neutrino_Vis.py",
        "docs/topics/0.7_Neutrino_Physics/Code/03_Research/Research_PMNS_Mixing.py",
        "docs/topics/0.7_Neutrino_Physics/Code/03_Research/Research_Thermo_Galaxy.py",
        "docs/topics/0.7_Neutrino_Physics/Code/04_Competitor/neutrino_solver.py",
        "docs/topics/0.7_Neutrino_Physics/Code/04_Competitor/run_neutrino_experiment.py",
    ],
    "Topic 8: Muon g-2": [
        "docs/topics/0.8_Muon_g2_Anomaly/Code/01_Engine/Engine_Muon_G2.py",
        "docs/topics/0.8_Muon_g2_Anomaly/Code/02_Proof/Proof_Muon_Anomaly.py",
        "docs/topics/0.8_Muon_g2_Anomaly/Code/03_Research/Research_Muon_Anomaly.py",
        "docs/topics/0.8_Muon_g2_Anomaly/Code/04_Competitor/run_muon_experiment.py",
    ],
    "Topic 9: Quantum Nonlocality": [
        "docs/topics/0.9_Quantum_Nonlocality/Code/01_Engine/Engine_Quantum.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/01_Engine/Engine_Quantum_LC_Unity.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/02_Proof/Proof_Bell_Violation.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/03_Research/Research_Bell_Test.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/03_Research/Research_Bell_Inequality.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/03_Research/Research_DNA_Tunneling_Decay.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/03_Research/Research_Double_Slit.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/03_Research/Research_Qubit_Mechanics.py",
        "docs/topics/0.9_Quantum_Nonlocality/Code/04_Competitor/Competitor_QM_Baseline.py",
    ],
    "Topic 10: Fluid Dynamics & Chaos": [
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/01_Engine/Engine_UET_2D.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/01_Engine/Engine_UET_3D.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/02_Proof/Proof_3D_Performance.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/02_Proof/Proof_Smoothness_3D.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/02_Proof/Proof_Turbulence_Benchmarks.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/02_Proof/Proof_UltraScale_3D.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/fetch_realtime_data.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_3D_Comparison.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_3D_Turbulence_Limits.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Artificial_Heart.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Brownian.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Calibration_Sweep.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Cosmic_Fluid_Turbulence.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Dashboard_Tool.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Earth_Gaia_Flow.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_FluidStatics_Buoyancy.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Hypersonic_Waverider.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Inertial_Fluid.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Inertial_Runner.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Legacy_Accuracy.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Legacy_Comparison.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Legacy_Runner.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_NS_Million_Cell.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_NS_Planck_Regulator.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_NS_Turbulence_Siege.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Realtime_Fluid.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_Tokamak_Fusion.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_TurbulenceStress_Test.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/03_Research/Research_VortexWake_Test.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/04_Competitor/Competitor_Benchmark_Suite.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/04_Competitor/Competitor_NS_2D.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/04_Competitor/Competitor_NS_2D_Improved.py",
        "docs/topics/0.10_Fluid_Dynamics_Chaos/Code/04_Competitor/Competitor_NS_3D.py",
    ],
    "Topic 11: Phase Transitions": [
        "docs/topics/0.11_Phase_Transitions/Code/01_Engine/Engine_Phase.py",
        "docs/topics/0.11_Phase_Transitions/Code/02_Proof/Proof_Order_Parameter.py",
        "docs/topics/0.11_Phase_Transitions/Code/03_Research/test_05_phase_demixing.py",
        "docs/topics/0.11_Phase_Transitions/Code/03_Research/test_phase_transitions.py",
        "docs/topics/0.11_Phase_Transitions/Code/04_Competitor/phase_solver.py",
        "docs/topics/0.11_Phase_Transitions/Code/04_Competitor/run_phase_experiment.py",
    ],
    "Topic 12: Vacuum Energy & Casimir": [
        "docs/topics/0.12_Vacuum_Energy_Casimir/Code/01_Engine/Engine_Vacuum.py",
        "docs/topics/0.12_Vacuum_Energy_Casimir/Code/02_Proof/Proof_Casimir_Force.py",
        "docs/topics/0.12_Vacuum_Energy_Casimir/Code/03_Research/casimir_test.py",
        "docs/topics/0.12_Vacuum_Energy_Casimir/Code/03_Research/Research_Casimir.py",
        "docs/topics/0.12_Vacuum_Energy_Casimir/Code/04_Competitor/casimir_solver.py",
        "docs/topics/0.12_Vacuum_Energy_Casimir/Code/04_Competitor/Competitor_Casimir_Baseline.py",
    ],
    "Topic 13: The Bridge (Thermodynamics)": [
        "docs/topics/0.13_Thermodynamic_Bridge/Code/01_Engine/Engine_Thermodynamics.py",
        "docs/topics/0.13_Thermodynamic_Bridge/Code/02_Proof/Proof_Entropy_Max.py",
        "docs/topics/0.13_Thermodynamic_Bridge/Code/03_Research/Proof_Vacuum_Entropy_Sink.py",
        "docs/topics/0.13_Thermodynamic_Bridge/Code/03_Research/Research_Landauer.py",
        "docs/topics/0.13_Thermodynamic_Bridge/Code/03_Research/Research_Real_Data_Validation.py",
        "docs/topics/0.13_Thermodynamic_Bridge/Code/03_Research/Research_Thermodynamic_Bridge.py",
    ],
    "Topic 14: Complex Systems": [
        "docs/topics/0.14_Complex_Systems/Code/01_Engine/Engine_Complexity.py",
        "docs/topics/0.14_Complex_Systems/Code/01_Engine/Engine_Econophysics.py",
        "docs/topics/0.14_Complex_Systems/Code/02_Proof/Proof_Power_Law.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Biology_HRV.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Brain.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Climate.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Complex_Systems.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Economic_Health.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Econophysics.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Global_Economy.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Inequality.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Ledgers.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Social.py",
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Thailand",  # Missing Py ext in user text but assumed
        "docs/topics/0.14_Complex_Systems/Code/03_Research/Research_Validation.py",
        "docs/topics/0.14_Complex_Systems/Code/04_Competitor/Baseline_Market_Experiment.py",
    ],
    "Topic 15: Cluster Dynamics": [
        "docs/topics/0.15_Cluster_Dynamics/Code/01_Engine/cluster_solver.py",
        "docs/topics/0.15_Cluster_Dynamics/Code/01_Engine/Engine_Cluster_Dynamics.py",
        "docs/topics/0.15_Cluster_Dynamics/Code/02_Proof/Proof_Virial_Mass.py",
        "docs/topics/0.15_Cluster_Dynamics/Code/03_Research/Research_BulletCluster_Offset.py",
        "docs/topics/0.15_Cluster_Dynamics/Code/03_Research/Research_Cluster_Virial.py",
        "docs/topics/0.15_Cluster_Dynamics/Code/03_Research/Research_Cluster_Formation.py",
        "docs/topics/0.15_Cluster_Dynamics/Code/03_Research/Research_Stability_Experiment.py",
    ],
    "Topic 16: Heavy Nuclei": [
        "docs/topics/0.16_Heavy_Nuclei/Code/01_Engine/Engine_Fission_Solver.py",
        "docs/topics/0.16_Heavy_Nuclei/Code/01_Engine/Engine_Heavy_Nuclei.py",
        "docs/topics/0.16_Heavy_Nuclei/Code/02_Proof/Proof_Stability_Valley.py",
        "docs/topics/0.16_Heavy_Nuclei/Code/03_Research/Research_Fission.py",
        "docs/topics/0.16_Heavy_Nuclei/Code/03_Research/Research_Heavy_Binding.py",
        "docs/topics/0.16_Heavy_Nuclei/Code/03_Research/Research_Heavy_Nuclei.py",
    ],
    "Topic 17: Mass Generation": [
        "docs/topics/0.17_Mass_Generation/Code/01_Engine/Engine_Mass_Higgs.py",
        "docs/topics/0.17_Mass_Generation/Code/02_Proof/Proof_Lepton_Mass.py",
        "docs/topics/0.17_Mass_Generation/Code/03_Research/Research_Mass_Mechanism.py",
        "docs/topics/0.17_Mass_Generation/Code/03_Research/Verify_Mass_Generation.py",
    ],
    "Topic 18: Mathnicry (Millennium Prize)": [
        "docs/topics/0.18_Mathnicry/Code/01_Engine/Engine_Collatz_Field.py",
        "docs/topics/0.18_Mathnicry/Code/01_Engine/Engine_Elliptic_Resonance.py",
        "docs/topics/0.18_Mathnicry/Code/01_Engine/Engine_Quantum_Logic.py",
        "docs/topics/0.18_Mathnicry/Code/01_Engine/Engine_Riemann_Field.py",
        "docs/topics/0.18_Mathnicry/Code/02_Proof/Audit_Quantum_Engine_Integrity.py",
        "docs/topics/0.18_Mathnicry/Code/02_Proof/Proof_Bell_State_Fidelity.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Hodge_Lattice_Topography.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_BSD_Elliptic_Unity.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Collatz_Unity.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Grover_Search_UET.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Lyapunov_Collatz.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_P_vs_NP_Scaling.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_P_vs_NP_Siege.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Qubit_Mechanics.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Riemann_Siege.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Riemann_Global_Stability.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Riemann_Zeta_UET.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_UET_Neural_Sieve.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Verify_Quantum_Logic.py",
        "docs/topics/0.18_Mathnicry/Code/03_Research/Research_Millennium_Grand_Slam.py",
    ],
    "Topic 19: Gravity & GR": [
        "docs/topics/0.19_Gravity_GR/Code/01_Engine/Engine_Fluid_Gravity.py",
        "docs/topics/0.19_Gravity_GR/Code/01_Engine/Engine_Gravity_GR.py",
        "docs/topics/0.19_Gravity_GR/Code/02_Proof/Proof_Equivalence_Principle.py",
        "docs/topics/0.19_Gravity_GR/Code/03_Research/Research_G_Constant.py",
    ],
    "Topic 20: Atomic Physics": [
        "docs/topics/0.20_Atomic_Physics/Code/01_Engine/Engine_Atomic_Hydrogen.py",
        "docs/topics/0.20_Atomic_Physics/Code/02_Proof/Proof_Hydrogen_Spectrum.py",
        "docs/topics/0.20_Atomic_Physics/Code/03_Research/Research_Multi_Electron.py",
        "docs/topics/0.20_Atomic_Physics/Code/03_Research/Research_Atomic_ThreeBody.py",
    ],
    "Topic 21: Mass Gap (Yang-Mills)": [
        "docs/topics/0.21_Yang_Mills_Mass_Gap/Code/01_Engine/Engine_Mass_Gap.py",
        "docs/topics/0.21_Yang_Mills_Mass_Gap/Code/02_Proof/Proof_Mass_Gap.py",
        "docs/topics/0.21_Yang_Mills_Mass_Gap/Code/03_Research/Research_Mass_Gap_Sweep.py",
        "docs/topics/0.21_Yang_Mills_Mass_Gap/Code/03_Research/Research_Mass_Gap.py",
        "docs/topics/0.21_Yang_Mills_Mass_Gap/Code/03_Research/Research_Quantum_Vortex.py",
    ],
    "Topic 22: Biophysics & Origin of Life": [
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/01_Engine/Engine_Biophysics_Neural.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/01_Engine/Engine_Biophysics.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/01_Engine/Engine_Life_Entropy.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/02_Proof/Proof_Neural_Complexity.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/02_Proof/Proof_Neural_Dynamics.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/02_Proof/Proof_Schrodinger_Life.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_Biomarker_Identification.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_Cancer_Cell_Chaos.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_Clinical_Strategy_Comparison.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_DNA_Entropy.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_HighFidelity_Tissue_Grid.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_Personalized_Threshold.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_Seizure_Prediction.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_TCell_Immunity.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/03_Research/Research_TCGA_Entropy_Map.py",
        "docs/topics/0.22_Biophysics_Origin_of_Life/Code/04_Competitor/Competitor_Cancer_Models.py",
    ],
    "Topic 23: Unity Scale Link": [
        "docs/topics/0.23_Unity_Scale_Link/Code/01_Engine/Engine_Derivation.py",
        "docs/topics/0.23_Unity_Scale_Link/Code/01_Engine/Engine_Unity_Scale.py",
        "docs/topics/0.23_Unity_Scale_Link/Code/02_Proof/Proof_Kappa_Unity.py",
        "docs/topics/0.23_Unity_Scale_Link/Code/03_Research/Falsification_Analysis.py",
        "docs/topics/0.23_Unity_Scale_Link/Code/03_Research/Research_Cross_Domain.py",
    ],
    "Topic 24: AI & Consciousness": [
        "docs/topics/0.24_Artificial_Intelligence/Code/01_Engine/UET_AI_Core.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/02_Proof/Proof_AI_Efficiency.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/02_Proof/Proof_Latent_Space.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_AI_Detective_V2.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_AI_Detective.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_AI_Scaling.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_Alignment_Equilibrium.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_Consciousness.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_Data_Verification.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_Foundation_Gen.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_NanoGPT_UET.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Research_SimpleLM_UET.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Quantum_Inspired_AI.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/03_Research/Verify_AI_Learning.py",
        "docs/topics/0.24_Artificial_Intelligence/Code/01_Engine/Benchmark_vs_Transformer.py",
    ],
    "Topic 25: Strategy & Power Economics": [
        "docs/topics/0.25_Strategy_Power_Economics/Code/01_Engine/Engine_Power_Dynamics.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/02_Proof/Proof_Social_Stability.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/fetch_realtime_data.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_8_Billion_Resonance.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_Ecosystem_Equilibrium.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_Global_Manifold_2024.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_Global_Scale_8B.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_Intellect_Economics.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_Leverage_Wave.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_Water_Synergy.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Research_World_Lease_Comparison.py",
        "docs/topics/0.25_Strategy_Power_Economics/Code/03_Research/Verify_Economy_Real.py",
    ],
    "Topic 26: Cosmic Dynamic Frame": [
        "docs/topics/0.26_Cosmic_Dynamic_Frame/Code/01_Engine/Engine_Dynamic_Universe_v1.py",
        "docs/topics/0.26_Cosmic_Dynamic_Frame/Code/02_Proof/Proof_Dynamic_Viscosity.py",
        "docs/topics/0.26_Cosmic_Dynamic_Frame/Code/03_Research/Proof_Toroidal_Cycle.py",
        "docs/topics/0.26_Cosmic_Dynamic_Frame/Code/03_Research/Research_Pioneer_Drag.py",
        "docs/topics/0.26_Cosmic_Dynamic_Frame/Code/03_Research/Research_Toroidal_Evolution.py",
        "docs/topics/0.26_Cosmic_Dynamic_Frame/Code/03_Research/Research_Unified_Cosmic_Theory.py",
    ],
    "Topic 27: Cold Light Hologram (Future Tech)": [
        "docs/topics/0.27_Cold_Light_Hologram/Code/01_Engine/Engine_Cold_Light.py",
        "docs/topics/0.27_Cold_Light_Hologram/Code/02_Proof/Proof_Resonance_Lock.py",
        "docs/topics/0.27_Cold_Light_Hologram/Code/03_Research/Research_Hologram_Stability.py",
        "docs/topics/0.27_Cold_Light_Hologram/Code/04_Competitor/Competitor_Standard_Slow_Light.py",
    ],
    "Topic 28: Material Synthesis (Graphene)": [
        "docs/topics/0.28_Material_Synthesis/Code/01_Engine/Engine_Flash_Joule.py",
        "docs/topics/0.28_Material_Synthesis/Code/01_Engine/Engine_Resonant_CVD.py",
        "docs/topics/0.28_Material_Synthesis/Code/02_Proof/Proof_Acoustic_Guidance.py",
        "docs/topics/0.28_Material_Synthesis/Code/02_Proof/Proof_Factory_Retrofit.py",
        "docs/topics/0.28_Material_Synthesis/Code/04_Competitor/Competitor_Random_CVD.py",
    ],
    "Topic 29: Ocean Recovery": [
        "docs/topics/0.29_Ocean_Recovery/Code/01_Engine/Engine_BioStructure.py",
        "docs/topics/0.29_Ocean_Recovery/Code/01_Engine/Engine_Ocean_Cooling.py",
        "docs/topics/0.29_Ocean_Recovery/Code/01_Engine/Engine_Ocean_Power.py",
        "docs/topics/0.29_Ocean_Recovery/Code/02_Proof/Proof_Carbon_Oxygen_ROI.py",
        "docs/topics/0.29_Ocean_Recovery/Code/02_Proof/Proof_Economic_Scale.py",
        "docs/topics/0.29_Ocean_Recovery/Code/02_Proof/Proof_Economic_Threshold.py",
        "docs/topics/0.29_Ocean_Recovery/Code/02_Proof/Proof_Global_Deployment.py",
        "docs/topics/0.29_Ocean_Recovery/Code/02_Proof/Proof_Self_Powered.py",
        "docs/topics/0.29_Ocean_Recovery/Code/02_Proof/Proof_Thermal_Shield.py",
        "docs/topics/0.29_Ocean_Recovery/Code/02_Proof/Proof_Zero_Waste.py",
    ],
    "Topic 30: Mega-Flora Biotech": [
        "docs/topics/0.30_Mega_Flora_Biotech/Code/01_Engine/Engine_Full_Ecosystem_Integration.py",
        "docs/topics/0.30_Mega_Flora_Biotech/Code/01_Engine/Engine_Growth_Simulation.py",
        "docs/topics/0.30_Mega_Flora_Biotech/Code/01_Engine/Engine_Mycelial_Network.py",
        "docs/topics/0.30_Mega_Flora_Biotech/Code/02_Proof/Proof_03_Integrated.py",
        "docs/topics/0.30_Mega_Flora_Biotech/Code/02_Proof/Proof_04_Bio_Housing.py",
        "docs/topics/0.30_Mega_Flora_Biotech/Code/02_Proof/Proof_Accelerated_Ecosystem.py",
        "docs/topics/0.30_Mega_Flora_Biotech/Code/02_Proof/Proof_Bio_Anchor.py",
    ],
    "Topic 31: SpaceTime Propulsion": [
        "docs/topics/0.31_SpaceTime_Propulsion/Code/01_Engine/Engine_Slingshot.py",
        "docs/topics/0.31_SpaceTime_Propulsion/Code/01_Engine/Engine_Slingshot_v2.py",
        "docs/topics/0.31_SpaceTime_Propulsion/Code/02_Proof/Proof_01_LightSpeed_Approach.py",
    ],
}
